### ISSUE TITLE
Example for custom model training

### ISSUE THREAD

**Issue by Selectorrr** [myshell-ai/OpenVoice#5]
Hi @Zengyi-Qin
The paper looks great. Unfortunately the pre-training model can only work with English, although the examples contain other languages as well, which is misleading.
I tried adding a new language by modifying the code (adding tags and a converter to phonemes) and even managed to synthesize audio, but unfortunately it only looks a bit like promt.
Are you planning to open access (add an example) to train a custom model so that the community can add their own languages and train the model on their own dataset?

**Comment by egoist-sx** [comment]
Will add examples soon.

**Comment by Zengyi-Qin** [comment]
The tone color converter now supports multiple language, no matter whether the language exists in the MSML training set. Please see `demo_part2.ipynb`. For the base speaker model, the community can directly train their VITS to add a new language. We will also provide a Chinese base speaker model soon.

**Comment by Zengyi-Qin** [comment]
Since there is no follow-up question from Selectorrr, the issue is marked temporarly closed.

**Comment by 9cento** [comment]
> Since there is no follow-up question from Selectorrr, the issue is marked temporarly closed.

How/where do I get Italian for text-to-speech?

**Comment by ordigital** [comment]
> The tone color converter now supports multiple languages, no matter whether the language exists in the MSML training set. Please see `demo_part2.ipynb`. For the base speaker model, the community can directly train their VITS to add a new language. We will also provide a Chinese base speaker model soon.

Are there any instructions how to «directly train VITS to add new language» that will allow checkpoint to be usable just as existing ones (EN, ZH) through api.py? With what tools EN i ZH models were trained and generated?

**Comment by ordigital** [comment]
> > Since there is no follow-up question from Selectorrr, the issue is marked temporarly closed.
> 
> How/where do I get Italian for text-to-speech?

A the moment the easiest way is to use any TTS with default voice speaking in your language that will be used as a base for cloning instead of paid OpenAI suggested in demo_part2.ipynb. I've tested it with coqui TTS using  xtts2 (using different base speaker than target speaker for OpenVoice), tts_models/pl/mai_female/vits and mms-tts using polish checkpoint but all effects of OpenVoice cloning was very poor and not even close to xtts2 voice cloning. I do not see in what way «can accurately clone the reference tone color and generate speech in multiple languages and accents». It doesn't seem to work for any TTS source except two bundled pre-trained checkpoints and there is no information about training and using other models at the moment.

**Comment by chazo1994** [comment]
Could you share the code for training or finetune the openvoice v2 model for unseen language.

**Comment by ismailgokhanuslu** [comment]
Can you please share the code/example/guide for training and adding a new base model for a new language?

**Comment by ismailgokhanuslu** [comment]
any chance to give some instructions for adding a new language to speak?
